### ISSUE TITLE
Documentation on bluetooth protocol ?

### ISSUE THREAD

**Issue by vincegre** [jzarca01/LILO#6]
Hi

I just discovered your python lib to control a Lilo potager ! Unhappy I'm not really goot at Python :( Do you have a little documentation on how it works or messages to send ? as I want to control it with Home Assistant and use some ESP to do the Bluetooth communication with Lilo ;)

Thanks a lot,

Vincèn

**Comment by jzarca01** [comment]
Have a look at this https://github.com/jzarca01/docker-lilo

This docker container can communicate back and forth with Home Assistant via MQTT

<img width="1241" alt="Capture d’écran 2022-11-22 à 20 13 07" src="https://user-images.githubusercontent.com/9349451/203401794-fb243eaa-7b62-4578-abda-a06bb547807f.png">
<img width="1232" alt="Capture d’écran 2022-11-22 à 20 13 25" src="https://user-images.githubusercontent.com/9349451/203401804-bfbf9655-49c5-4cf6-82fa-be90f7620202.png">
<img width="1232" alt="Capture d’écran 2022-11-22 à 20 13 25" src="https://user-images.githubusercontent.com/9349451/203401906-5053be90-3107-4a67-9037-db64620264b7.png">

**Comment by vincegre** [comment]
> Have a look at this https://github.com/jzarca01/docker-lilo
> 
> This docker container can communicate back and forth with Home Assistant via MQTT

sorry for the late answer (have been overbusy with work) and yep it could be a solution but unhappy I'm running HA in OS version so I can't install additional docker :( I'll check source of your code and find out if I can find a way to interface Lilo with an ESP as it's using BLE for communication !
Thanks for your answer ;)

**Comment by jzarca01** [comment]
you don't need to run this container on the same unit, just make sure to configure the mqtt address properly
